### PR TITLE
Incorporate dbAppendTable function

### PR DESCRIPTION
**Pull request by JSchoenbachler**

### CODE REVIEW

**Comment by JSchoenbachler** [comment]
@tridelt Here is a pull request for the dbAppendTable function. Disregard all commits prior to https://github.com/IMSMWU/RClickhouse/pull/73/commits/ea2a458c724edfd69749badfdf1e1565c27450f3, that was a pull request where I reset everything to this branch before adding the dbAppendTable function.

**Comment by JSchoenbachler** [comment]
It's failing CI checks, give me a second to spin up a new environment and run some tests.

**Comment by JSchoenbachler** [comment]
@tridelt Sorry about the pull request fail as I created. I wasn't passing the correct parameter values into the method call in the test function, but it is fixed now.

**Comment by JSchoenbachler** [comment]
#71

**Comment by tridelt** [comment]
thank you for your effort. I will check it out in the morning.

**Comment by tridelt** [comment]
looks good! Also, thank you very much for including a test-case.
I will merge it into the pull request #72 for the [dbCreate_dbAppend](https://github.com/IMSMWU/RClickhouse/tree/dbCreate_dbAppend)

**Pull request merged**
